// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// AirplaneGetParkingSpotParams is parameters of airplane_getParkingSpot operation.
type AirplaneGetParkingSpotParams struct {
	// ID самолета.
	ID string
}

func unpackAirplaneGetParkingSpotParams(packed middleware.Parameters) (params AirplaneGetParkingSpotParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodeAirplaneGetParkingSpotParams(args [1]string, argsEscaped bool, r *http.Request) (params AirplaneGetParkingSpotParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// MovingRegisterVehicleParams is parameters of moving_registerVehicle operation.
type MovingRegisterVehicleParams struct {
	// Тип транспорта.
	Type VehicleType
}

func unpackMovingRegisterVehicleParams(packed middleware.Parameters) (params MovingRegisterVehicleParams) {
	{
		key := middleware.ParameterKey{
			Name: "type",
			In:   "path",
		}
		params.Type = packed[key].(VehicleType)
	}
	return params
}

func decodeMovingRegisterVehicleParams(args [1]string, argsEscaped bool, r *http.Request) (params MovingRegisterVehicleParams, _ error) {
	// Decode path: type.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "type",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Type = VehicleType(c)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.Type.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "type",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
