// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AirplaneGetParkingSpotOperation OperationName = "AirplaneGetParkingSpot"
	MapGetAirportMapOperation       OperationName = "MapGetAirportMap"
	MapGetAirportMapConfigOperation OperationName = "MapGetAirportMapConfig"
	MapRefreshAirportMapOperation   OperationName = "MapRefreshAirportMap"
	MapUpdateAirportMapOperation    OperationName = "MapUpdateAirportMap"
	MovingGetRouteOperation         OperationName = "MovingGetRoute"
	MovingNotifyArrivalOperation    OperationName = "MovingNotifyArrival"
	MovingRegisterVehicleOperation  OperationName = "MovingRegisterVehicle"
	MovingRequestMoveOperation      OperationName = "MovingRequestMove"
)
