// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AirplaneGetParkingSpotOperation   OperationName = "AirplaneGetParkingSpot"
	AirplaneIDServiceTypeGetOperation OperationName = "AirplaneIDServiceTypeGet"
	MapAddEdgeOperation               OperationName = "MapAddEdge"
	MapAddNodeOperation               OperationName = "MapAddNode"
	MapGetAirportMapOperation         OperationName = "MapGetAirportMap"
	MovingGetRouteOperation           OperationName = "MovingGetRoute"
	MovingNotifyArrivalOperation      OperationName = "MovingNotifyArrival"
	MovingRegisterVehicleOperation    OperationName = "MovingRegisterVehicle"
	MovingRequestMoveOperation        OperationName = "MovingRequestMove"
)
