// Code generated by ogen, DO NOT EDIT.
package api

type AirplaneGetParkingSpotRes interface {
	airplaneGetParkingSpotRes()
}

type AirplaneTakeOffRes interface {
	airplaneTakeOffRes()
}

type MapUpdateAirportMapRes interface {
	mapUpdateAirportMapRes()
}

type MovingGetRouteRes interface {
	movingGetRouteRes()
}

type MovingNotifyArrivalRes interface {
	movingNotifyArrivalRes()
}

type MovingRegisterVehicleRes interface {
	movingRegisterVehicleRes()
}

type MovingRequestMoveRes interface {
	movingRequestMoveRes()
}
