// Code generated by ogen, DO NOT EDIT.
package api

type AirplaneGetParkingSpotRes interface {
	airplaneGetParkingSpotRes()
}

type AirplaneIDServiceTypeGetRes interface {
	airplaneIDServiceTypeGetRes()
}

type MapAddEdgeRes interface {
	mapAddEdgeRes()
}

type MapAddNodeRes interface {
	mapAddNodeRes()
}

type MovingGetRouteRes interface {
	movingGetRouteRes()
}

type MovingNotifyArrivalRes interface {
	movingNotifyArrivalRes()
}

type MovingRegisterVehicleRes interface {
	movingRegisterVehicleRes()
}

type MovingRequestMoveRes interface {
	movingRequestMoveRes()
}
